### ISSUE TITLE
CK-Caffe installation fails due to an HDF5 dependency

### ISSUE THREAD

**Issue by psyhtest** [dividiti/ck-caffe#1]
On Odroid-XU3, HDF5 library files get installed into `/usr/lib/arm-linux-gnueabihf/hdf5/serial/`:

```
$ dpkg -L libhdf5-dev
...
/usr/lib/arm-linux-gnueabihf/hdf5/serial/libhdf5.so
...
/usr/lib/arm-linux-gnueabihf/hdf5/serial/libhdf5_hl.so
```

The standard Caffe `Makefile.config`, however, hardcodes the library paths as follows:

```
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/x86_64-linux-gnu/hdf5/serial
```

Should create a CK description for HDF5 and use it instead as e.g.

```
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib  $(CK_ENV_LIB_HDF5_LIB)
```

**Comment by psyhtest** [comment]
A trivial workaround is of course:

```
# ln -s /usr/lib/arm-linux-gnueabihf /usr/lib/x86_64-linux-gnu
```

**Comment by psyhtest** [comment]
On another platform, HDF5 was found in `/usr/local/HDF_Group/HDF5/1.8.17/lib` under the name of `libhdf5-shared.so`, so the problem is not unique to Odroid-XU3.

**Comment by gfursin** [comment]
I added soft:lib.hdf5 to ck-env repo. To check:

$ ck pull repo:ck-env
$ ck check soft:lib.hdf5

I search for libhdf5.so and then detect include directory with hdf5.h

Environment set:
- CK_ENV_LIB_HDF5_LIB
- CK_ENV_LIB_HDF5_INCLUDE

You may now try to add it to CK-CAFFE as deps and update cmake ...
Please, tell me if you need further help ...

**Comment by psyhtest** [comment]
@gfursin Thanks! I've successfully tested this on the Odroid-XU3 and an x86-64 laptop.

Just a little niggle. On the laptop, the environment paths look like:

```
export CK_ENV_LIB_HDF5_LIB=/usr/lib/x86_64-linux-gnu/hdf5/serial
export CK_ENV_LIB_HDF5_INCLUDE=/usr/lib/x86_64-linux-gnu/hdf5/serial/include
```

The latter is actually a symbolic link to `../../../../include/hdf5/serial`, which turns out to be `/usr/include/hdf5/serial/`. It would be a bit less confusing to write that into the environment directly but I guess it depends on the order in which CK detects file locations...

Also, another variable gets set:

```
export CK_ENV_LIB_HDF5=/usr/lib/x86_64-linux-gnu/hdf5/serial/include
```

I'd expect this variable to point to the library directory rather than to the include directory.

**Comment by gfursin** [comment]
I have fixed all that right now. I also improved output of the detect soft module ... Please, update all repos (ck pull all --kernel) and try again ... Thanks!
P.S. CK_ENV_LIB_HDF5 is a bit ambiguous environment, so I suggest not to rely on it - originally it was the path to the root directory where lib, include, bin resides, but now, when we automatically detect soft, there is often no root directory (just like in the above case), so it's not clear what to write there. I put Lib as you asked, but you should use CK_ENV_LIB_HDF5_LIB for the lib path ...

**Comment by psyhtest** [comment]
It looks much nicer now with:

```
export CK_ENV_LIB_HDF5_LIB=/usr/lib/arm-linux-gnueabihf/hdf5/serial
export CK_ENV_LIB_HDF5_INCLUDE=/usr/include/hdf5/serial
```

instead of:

```
export CK_ENV_LIB_HDF5_LIB=/usr/lib/arm-linux-gnueabihf/hdf5/serial
export CK_ENV_LIB_HDF5_INCLUDE=/usr/lib/arm-linux-gnueabihf/hdf5/serial/include
```

Thanks! I've added HD5 dependencies to all the Caffe packages now, and it works a charm so far.

As for `CK_ENV_LIB_HDF5`, if some software relies on `lib` and `include` to have  a common parent dir, on Linux it can always access the parent dir as `${CK_ENV_LIB_HDF5_LIB}/..` or `${CK_ENV_LIB_HDF5_INCLUDE}/..` (which should be as easy on Windows?)

On the other hand, perhaps having another variable `CK_ENV_LIB_HDF5_ROOT` that would only be set only if there's a common parent dir would allow to distinguish potentially problematic cases for such software? Just a closing thought...
