### ISSUE TITLE
Do you plan to add caffe2 to your framework?

### ISSUE THREAD

**Issue by mlosab3** [dividiti/ck-caffe#102]
See https://github.com/caffe2/caffe2/issues/285 & https://github.com/caffe2/caffe2/issues/292

**Comment by gfursin** [comment]
I just saw the announcement so we did not think about it yet ;) ... However looking at the caffe2 description, it should not be very difficult to add it using current CK packages as example:
* https://github.com/dividiti/ck-caffe/tree/master/package
* https://github.com/dividiti/ck-caffe/blob/master/package/lib-caffe-bvlc-master-cpu-universal/.cm/meta.json

While we don't quite have time to do it right now, please feel free to try it and ask questions if you have any troubles ...

**Comment by psyhtest** [comment]
@gfursin, you forgot to mention here that you have recently added it: http://github.com/ctuning/ck-caffe2 :)

**Comment by mlosab3** [comment]
my apologies for not staying in touch. certainly I shall look at it after my internship. i like your idea to develop a common api for caffe2 and caffe.
