### ISSUE TITLE
pthread error during "ck install"

### ISSUE THREAD

**Issue by kindloaf** [dividiti/ck-caffe#103]
Hi,
I'm trying to "ck install":
`ck install package:lib-caffe-bvlc-opencl-libdnn-clblast-universal`, and saw the following error:

> /usr/bin/gcc-4.9.real     -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTryCompileExec2370386294.dir/CheckFunctionExists.c.o  -o cm    TryCompileExec2370386294 -rdynamic -lpthreads
>/usr/bin/ld.bfd.real: cannot find -lpthreads
>...
>make[1]: Leaving directory `/home/.../CK-TOOLS/lib-caffe-bvlc-opencl-libdnn-clblast-trunk-gcc-4.9.4-linux-64/obj/CMakeFiles/CMakeTmp'

When I changed to `/home/.../CK-TOOLS/lib-caffe-bvlc-opencl-libdnn-clblast-trunk-gcc-4.9.4-linux-64/obj/CMakeFiles/CMakeTmp`, I didn't see any file. I couldn't locate file CheckFunctionExists.c.o

Any advice on how to fix this?

**Comment by psyhtest** [comment]
Often this can be resolved by installing `libboost-dev` e.g.
```
$ sudo apt-get install libboost-dev
```
Does this work for you?

**Comment by gfursin** [comment]
By the way, @kindloaf , what is the platform (OS,CPU)? I just never encountered this issue before ...

**Comment by psyhtest** [comment]
@kindloaf Do you still have this issue please?

**Comment by kindloaf** [comment]
@psyhtest Sorry for the late reply. I haven't got a chance to test it. I will close the issue for now.
Thanks for your help.
