### ISSUE TITLE
Fail to install ck-caffe

### ISSUE THREAD

**Issue by twang15** [dividiti/ck-caffe#107]
Following the installation guide (ck-caffe on ubuntu 16.04), 

after running "ck pull repo:ck-caffe --url=https://github.com/dividiti/ck-caffe"

Error occurs:
******************************************************************
Updating repo "ck-caffe" ...

  Local path: /home/tao/CK/ck-caffe
  URL:        https://github.com/dividity/ck-caffe

  cd /home/tao/CK/ck-caffe
  git pull

fatal: Not a git repository (or any of the parent directories): .git

 WARNING: repository update likely failed OR IN A DIFFERENT BRANCH/CHECKOUT (git exit code: 32768)

**Comment by psyhtest** [comment]
@twang15 Thanks for reporting! I can see that the URL is wrong during the update (it should contain "dividiti", not "dividity"). Not sure how that could happen but I will check all repos...

**Comment by psyhtest** [comment]
@twang15 
Could you please also share the output of:
```
$ ck show repo
```
Thanks!

**Comment by twang15** [comment]
Here is the result:

Please wait - it may take some time ...

ctuning-programs         ( master ; 5fb023f ; https://github.com/ctuning/ctuning-programs )
ck-dissemination-modules ( master ; 2c1f96e ; https://github.com/ctuning/ck-dissemination-modules )
ctuning-datasets-min     ( master ; 520ac1f ; https://github.com/ctuning/ctuning-datasets-min )
ck-caffe                 (  ;  ; https://github.com/dividity/ck-caffe )
ck-env                   ( master ; 3718ad5 ; https://github.com/ctuning/ck-env )
ck-analytics             ( master ; 5a8dcea ; https://github.com/ctuning/ck-analytics )
ck-crowdtuning-platforms ( master ; 101a2d0 ; https://github.com/ctuning/ck-crowdtuning-platforms )
ck-autotuning            ( master ; 7f5cbd3 ; https://github.com/ctuning/ck-autotuning )
reproduce-ck-paper       ( master ; 74cc7b4 ; https://github.com/ctuning/reproduce-ck-paper )
ck-web                   ( master ; 75d0783 ; https://github.com/ctuning/ck-web )
ck-crowdtuning           ( master ; e377300 ; https://github.com/ctuning/ck-crowdtuning )

**Comment by psyhtest** [comment]
@twang15 
As you can see, `ck-caffe` is the only repository for which a specific branch and revision are not shown! Again, I have no idea how this could have happened :( but can you please try to reinstall CK-Caffe as follows:
```
$ ck rm repo:ck-caffe
$ rm -rf $HOME/CK/ck-caffe
$ ck pull repo:ck-caffe --url=https://github.com/dividiti/ck-caffe
```

**Comment by twang15** [comment]
It works after following your instructions.
Thanks a lot!

**Comment by gfursin** [comment]
By the way, CK should fail when pulling non-existent GitHub repo. It's a bug so thanks @twang15 for finding it - I opened a ticket for CK and will try to fix it for the next release: https://github.com/ctuning/ck/issues/77
