### ISSUE TITLE
No Clablast library installed in lib-caffe-bvlc-opencl-clblast-universal package

### ISSUE THREAD

**Issue by abhi1212** [dividiti/ck-caffe#120]
Whenever we run the command ck install package:lib-caffe-bvlc-opencl-clblast-universal, we get Caffe without CLBLAST library installed.
Are we supposed to comment the line DUSE_LIBDNN:BOOL=${USE_LIBDNN} in the install script?

**Comment by gfursin** [comment]
Is it possible to get a log, please? 

If it's too large, can you can please invoke "ck install package:lib-caffe-bvlc-opencl-clblast-universal" again and just send me info with how CK resolved dependencies. 

Also can you please send the output of 
```
$ ck show env --tags=clblast
```

Finally, I recently added a stable package for Caffe OpenCL with CLBlast (all dependencies are compiled so it may take some time). Can you please try it too:
```
$ ck install package:lib-caffe-bvlc-opencl-clblast-universal-20171015
```

Lastly, can you please tell me about the platform and OS you are using? Thanks!

**Comment by abhi1212** [comment]
Thanks a lot @gfursin , I will send the log and try the new package as quickly as possible. 
Well , I am using an Intel server with a Quadro Gpu
Os- LInux, Ubuntu 64 bit

**Comment by abhi1212** [comment]
So, I ran the command again and this is how ck resolves the dependancy

Resolving software dependencies ...

*** Dependency 1 = cmake (cmake):

    Resolved. CK environment UID = 4ce088373b84c775 (detected version 3.5.1)

*** Dependency 2 = compiler (C++ compiler):

    Resolved. CK environment UID = aa2445c08a129029 (detected version 5.4.0)

*** Dependency 3 = lib-opencl (OpenCL stubs library):

    Resolved. CK environment UID = b6366f46b1b4eb71

*** Dependency 4 = lib-gflags (GFlags library):

    Resolved. CK environment UID = 093614ef18eea9f2

*** Dependency 5 = lib-glog (GLog library):

    Resolved. CK environment UID = 2941abafce842b6d

*** Dependency 6 = lib-lmdb (LMDB library):

    Resolved. CK environment UID = a6222da4b3981f2c

*** Dependency 7 = lib-hdf5 (HDF5 library):

    Resolved. CK environment UID = e436e5799e45a18e

*** Dependency 8 = lib-opencv (OpenCV library):

    Resolved. CK environment UID = 46930b7044fe1814

*** Dependency 9 = lib-boost (Boost library):

    Resolved. CK environment UID = 428598e466408a68

*** Dependency 10 = lib-blas (BLAS library):

    Resolved. CK environment UID = 3c9cc758fd8f4196

*** Dependency 11 = lib-viennacl (ViennaCL library):

    Resolved. CK environment UID = 4117936cca1ce737

*** Dependency 12 = lib-clblast (CLBlast library):

    Resolved. CK environment UID = 5483bd6874734331

*** Dependency 13 = lib-protobuf-host (ProtoBuf host compiler):

    Resolved. CK environment UID = f4cf7a72139d5991
  -----------------------------------

Searching if CK environment for this package already exists using:
  * Tags: lib,caffe,bvlc,vopencl,vclblast,host-os-linux-64,target-os-linux-64,64bits
  * Dependency: lib-protobuf-host=f4cf7a72139d5991
  * Dependency: lib-viennacl=4117936cca1ce737
  * Dependency: cmake=4ce088373b84c775
  * Dependency: lib-glog=2941abafce842b6d
  * Dependency: lib-opencv=46930b7044fe1814
  * Dependency: lib-opencl=b6366f46b1b4eb71
  * Dependency: lib-hdf5=e436e5799e45a18e
  * Dependency: lib-blas=3c9cc758fd8f4196
  * Dependency: lib-gflags=093614ef18eea9f2
  * Dependency: lib-clblast=5483bd6874734331
  * Dependency: lib-lmdb=a6222da4b3981f2c
  * Dependency: lib-boost=428598e466408a68
  * Dependency: compiler=aa2445c08a129029

CK environment found for this package: a188c74013a9bfaf

  OVERWRITING AND PROCESSING AGAIN!

*** Installation path used: /home/LAB/anikam/CK-TOOLS/lib-caffe-bvlc-opencl-clblast-master-gcc-5.4.0-linux-64


  -----------------------------------
  Resolving software dependencies ...

*** Dependency 1 = cmake (cmake):

    Resolved. CK environment UID = 4ce088373b84c775 (detected version 3.5.1)

*** Dependency 2 = compiler (C++ compiler):

    Resolved. CK environment UID = aa2445c08a129029 (detected version 5.4.0)

*** Dependency 3 = lib-opencl (OpenCL stubs library):

    Resolved. CK environment UID = b6366f46b1b4eb71

*** Dependency 4 = lib-gflags (GFlags library):

    Resolved. CK environment UID = 093614ef18eea9f2

*** Dependency 5 = lib-glog (GLog library):

    Resolved. CK environment UID = 2941abafce842b6d

*** Dependency 6 = lib-lmdb (LMDB library):

    Resolved. CK environment UID = a6222da4b3981f2c

*** Dependency 7 = lib-hdf5 (HDF5 library):

    Resolved. CK environment UID = e436e5799e45a18e

*** Dependency 8 = lib-opencv (OpenCV library):

    Resolved. CK environment UID = 46930b7044fe1814

*** Dependency 9 = lib-boost (Boost library):

    Resolved. CK environment UID = 428598e466408a68

*** Dependency 10 = lib-blas (BLAS library):

    Resolved. CK environment UID = 3c9cc758fd8f4196

*** Dependency 11 = lib-viennacl (ViennaCL library):

    Resolved. CK environment UID = 4117936cca1ce737

*** Dependency 12 = lib-clblast (CLBlast library):

    Resolved. CK environment UID = 5483bd6874734331

*** Dependency 13 = lib-protobuf-host (ProtoBuf host compiler):

    Resolved. CK environment UID = f4cf7a72139d5991

**Comment by abhi1212** [comment]
Also, the ck install package:lib-caffe-bvlc-opencl-clblast-universal-20171015 did not work, I reckon I need to pull the repo again for that, I got a 
**can't find path to CK entry "package:lib-caffe-bvlc-opencl-clblast-universal-20171015" (?:1dc07ee0f4742028:?)!** error.

**Comment by abhi1212** [comment]
This is the output for ck show env --tags=clblast

![image](https://user-images.githubusercontent.com/22337618/31791530-d4cea21c-b4e6-11e7-9f91-728184a73afc.png)

**Comment by gfursin** [comment]
Hmm, CLBLast seems to be installed fine. How did you check that Caffe was installed without CLBlast? 

You can try a simple OpenCL benchmark to check that it works:
```
$ ck compile program:caffe-time-opencl
$ ck run program:caffe-time-opencl
```
Usually, when OpenCL-based installation is broken, it fails too ... The first run can be a bit slow due to internal kernel caching but subsequent runs are usually much faster ...

LIBDNN is another library which can work with or without CLBLAST and we had another package which turns both of them on (but it was not tested thoroughly though):
```
$ ck install package:lib-caffe-bvlc-opencl-libdnn-clblast-universal
```

As for the stable package I mentioned, you can update all CK repos as following (and then try again):
```
$ ck pull all
$ ck install package:lib-caffe-bvlc-opencl-clblast-universal-20171015
```

I actually checked this package recently on x86 and ARM64 machines and it seem to be working ...

**Comment by abhi1212** [comment]
Thanks a lot @gfursin for your prompt reply, there are multiple new functions supported by Clblast library such as *Xgemmbatched*. I cannot find a way for using these apis like Xgemmbatched with Caffe.
I said it is not installed with Caffe because I cannot find any CLBLAST files inside the :lib-caffe-bvlc-opencl-clblast-universal-20171015 package.
I request you to please guide me in using the Clbast apis for Caffe.

**Comment by psyhtest** [comment]
@abhi1212 A CK package is just a recipe to download, build and install a piece of software, while resolving its dependencies. The actual files get installed into a folder at `$HOME/CK-TOOLS` (or into `$CK_TOOLS` if this env variable is defined).

**Comment by gfursin** [comment]
Yes, CLBlast is installed in a separate place and then linked dynamically. The point of CK is to let you reuse various installations of libs in your projects. @psyhtest - maybe you can provide a few notes about which functions are currently used from CLBlast in the Caffe OpenCL branch, and where they are linked? I think it's done via ViennaCL API? Thanks!

**Comment by abhi1212** [comment]
Thanks a lot @psyhtest and @gfursin for your detailed explanation, I seem to have an idea about the flow.
It would really be helpful if @psyhtest can provide me with some notes on which functions are currently used from CLBlast in the Caffe OpenCL branch, and where they are linked.
I searched a lot but could not find any documentation on that.
Thanks

**Comment by gfursin** [comment]
BTW, I just saw your ticket #119 (I somehow missed it - we now have a very intense project with very close deadlines) - I saw @psyhtest answered there.  Maybe @CNugteren and @naibaf7 can provide more details about which CLBlast functions are currently used in the Caffe OpenCL branch ...

**Comment by abhi1212** [comment]
Thanks a lot @gfursin , your help is much appreciated.
