### ISSUE TITLE
Could NOT find OpenCL (missing: OPENCL_INCLUDE_DIRS) on firefly rk3399 board

### ISSUE THREAD

**Issue by dohai90** [dividiti/ck-caffe#122]
Hello,
Recently, I've tried to install ck-caffe on firefly rk3399 but faced this issue.
This is the resolved dependencies log:

`Resolved. CK environment UID = 3e77b64c02a943c4

*** Dependency 7 = lib-hdf5 (HDF5 library):

    Resolved. CK environment UID = c4d0c97f4ae5794c

*** Dependency 8 = lib-opencv (OpenCV library):

    Resolved. CK environment UID = 237eef707481d955

*** Dependency 9 = lib-boost (Boost library):

    Resolved. CK environment UID = a98cba54b49b9fae

*** Dependency 10 = lib-blas (BLAS library):

    Resolved. CK environment UID = 0be114d7bb052a1a

*** Dependency 11 = lib-viennacl (ViennaCL library):

    Resolved. CK environment UID = 2161864d16b40966

*** Dependency 12 = lib-clblast (CLBlast library):

    Resolved. CK environment UID = 0e9ecf84e6e9a0c5

*** Dependency 13 = lib-protobuf-host (ProtoBuf host compiler):

    Resolved. CK environment UID = 73d9c4e908f61532
  -----------------------------------

Searching if CK environment for this package already exists using:
  * Tags: lib,caffe,bvlc,vopencl,vclblast,host-os-linux-64,target-os-linux-64,64bits
  * Dependency: lib-protobuf-host=73d9c4e908f61532
  * Dependency: lib-viennacl=2161864d16b40966
  * Dependency: cmake=822f2eb104c2ba83
  * Dependency: lib-glog=08546c38efe8779a
  * Dependency: lib-opencv=237eef707481d955
  * Dependency: lib-opencl=a44911ecc006c67d
  * Dependency: lib-hdf5=c4d0c97f4ae5794c
  * Dependency: lib-blas=0be114d7bb052a1a
  * Dependency: lib-gflags=a498f9e7ad07585d
  * Dependency: lib-clblast=0e9ecf84e6e9a0c5
  * Dependency: lib-lmdb=3e77b64c02a943c4
  * Dependency: lib-boost=a98cba54b49b9fae
  * Dependency: compiler=554de4bc04f652b9

CK environment not found for this package ...

*** Installation path used: /home/firefly/CK-TOOLS/lib-caffe-bvlc-opencl-clblast-master-gcc-5.4.0-linux-64

  -----------------------------------
  Resolving software dependencies ...

*** Dependency 1 = cmake (cmake):

    Resolved. CK environment UID = 822f2eb104c2ba83 (detected version 3.5.1)

*** Dependency 2 = compiler (C++ compiler):

    Resolved. CK environment UID = 554de4bc04f652b9 (detected version 5.4.0)

*** Dependency 3 = lib-opencl (OpenCL library (stubs on Android)):

    Resolved. CK environment UID = a44911ecc006c67d

*** Dependency 4 = lib-gflags (GFlags library):

    Resolved. CK environment UID = a498f9e7ad07585d

*** Dependency 5 = lib-glog (GLog library):

    Resolved. CK environment UID = 08546c38efe8779a

*** Dependency 6 = lib-lmdb (LMDB library):

    Resolved. CK environment UID = 3e77b64c02a943c4

*** Dependency 7 = lib-hdf5 (HDF5 library):

    Resolved. CK environment UID = c4d0c97f4ae5794c

*** Dependency 8 = lib-opencv (OpenCV library):

    Resolved. CK environment UID = 237eef707481d955

*** Dependency 9 = lib-boost (Boost library):

    Resolved. CK environment UID = a98cba54b49b9fae

*** Dependency 10 = lib-blas (BLAS library):

    Resolved. CK environment UID = 0be114d7bb052a1a

*** Dependency 11 = lib-viennacl (ViennaCL library):

    Resolved. CK environment UID = 2161864d16b40966

*** Dependency 12 = lib-clblast (CLBlast library):

    Resolved. CK environment UID = 0e9ecf84e6e9a0c5

*** Dependency 13 = lib-protobuf-host (ProtoBuf host compiler):

    Resolved. CK environment UID = 73d9c4e908f61532
  -----------------------------------

Installing to /home/firefly/CK-TOOLS/lib-caffe-bvlc-opencl-clblast-master-gcc-5.4.0-linux-64

Cloning package from https://github.com/BVLC/caffe/ ...
Cloning into 'src'...
remote: Counting objects: 52083, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 52083 (delta 3), reused 2 (delta 1), pack-reused 52072
Receiving objects: 100% (52083/52083), 62.29 MiB | 395.00 KiB/s, done.
Resolving deltas: 100% (35014/35014), done.
Checking connectivity... done.

Checking out branch opencl ...

Branch opencl set up to track remote branch opencl from origin.
Switched to a new branch 'opencl'

Cleaning ...

Executing extra script ...
**************************************************************
Preparing vars for Caffe ...

You are compiling Caffe with Python support!
To use it you need to set up CK env as following (after installation):

ck xset env tags=lib,caffe ; . ./tmp-ck-env.bat ; ipython2

Press enter to continue
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106400
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:127 (include)

CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106400
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:127 (include)

CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106400
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:127 (include)

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
-- Found GFlags: /home/firefly/CK-TOOLS/lib-gflags-2.2.0-gcc-5.4.0-linux-64/install/include  
-- Found gflags  (include: /home/firefly/CK-TOOLS/lib-gflags-2.2.0-gcc-5.4.0-linux-64/install/include, library: /home/firefly/CK-TOOLS/lib-gflags-2.2.0-gcc-5.4.0-linux-64/install/lib/libgflags.so)
-- Found Glog: /home/firefly/CK-TOOLS/lib-glog-0.3.5-gcc-5.4.0-linux-64/install/include  
-- Found glog    (include: /home/firefly/CK-TOOLS/lib-glog-0.3.5-gcc-5.4.0-linux-64/install/include, library: /home/firefly/CK-TOOLS/lib-glog-0.3.5-gcc-5.4.0-linux-64/install/lib/libglog.so)
-- Found PROTOBUF: /home/firefly/CK-TOOLS/lib-protobuf-host-3.1.0-linux-64/install/lib/libprotobuf.a  
-- Found PROTOBUF Compiler: /home/firefly/CK-TOOLS/lib-protobuf-host-3.1.0-linux-64/install/bin/protoc
-- Found HDF5: /usr/lib/aarch64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/aarch64-linux-gnu/hdf5/serial/libhdf5_hl.so;/usr/lib/aarch64-linux-gnu/hdf5/serial/lib/libhdf5_hl.so;/usr/lib/aarch64-linux-gnu/hdf5/serial/lib/libhdf5.so;/usr/lib/aarch64-linux-gnu/libpthread.so;/usr/lib/aarch64-linux-gnu/libsz.so;/usr/lib/aarch64-linux-gnu/libz.so;/usr/lib/aarch64-linux-gnu/libdl.so;/usr/lib/aarch64-linux-gnu/libm.so (found version "1.8.16") 
-- Found LMDB: /home/firefly/CK-TOOLS/lib-lmdb-0.9.21-gcc-5.4.0-linux-64/install/include  
-- Found lmdb    (include: /home/firefly/CK-TOOLS/lib-lmdb-0.9.21-gcc-5.4.0-linux-64/install/include, library: /home/firefly/CK-TOOLS/lib-lmdb-0.9.21-gcc-5.4.0-linux-64/install/lib/liblmdb.so)
-- Found LevelDB: /usr/include  
-- Found LevelDB (include: /usr/include, library: /usr/lib/aarch64-linux-gnu/libleveldb.so)
-- Found Snappy: /usr/include  
-- Found Snappy  (include: /usr/include, library: /usr/lib/aarch64-linux-gnu/libsnappy.so)
-- -- CUDA is disabled. Building without it...
-- Found ViennaCL include: /home/firefly/CK-TOOLS/lib-viennacl-1.7.1-linux-64/src
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenCL (missing: OPENCL_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindOpenCL.cmake:154 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/Modules/FindViennaCL.cmake:37 (find_package)
  cmake/Dependencies.cmake:116 (find_package)
  CMakeLists.txt:127 (include)

-- Configuring incomplete, errors occurred!
See also "/home/firefly/CK-TOOLS/lib-caffe-bvlc-opencl-clblast-master-gcc-5.4.0-linux-64/obj/CMakeFiles/CMakeOutput.log".
See also "/home/firefly/CK-TOOLS/lib-caffe-bvlc-opencl-clblast-master-gcc-5.4.0-linux-64/obj/CMakeFiles/CMakeError.log".
Error: cmake failed!
CK error: [package] package installation failed!
`

I have install opencl headers by:
`$ sudo apt install ocl-icd-libopencl1`
`$ sudo apt install opencl-headers`
`$ sudo apt install clinfo`
`$ sudo apt install ocl-icd-opencl-dev`

And checked in `/user/inlcude/CL`:
`firefly@firefly:/usr/include/CL$ ls`
`cl.h  cl2.hpp  cl_d3d10.h  cl_d3d11.h  cl_dx9_media_sharing.h  cl_egl.h  cl_ext.h  cl_gl.h  cl_gl_ext.h  cl_platform.h  opencl.h
`
Could you help me find out why ck-caffe can not find OpenCL?

Thanks and Best regards

**Comment by psyhtest** [comment]
@dohai90 Many thanks for providing the log, it's very helpful.

I am guessing CK couldn't detect `libOpenCL.so` on your system, so resolved the OpenCL dependency in an incorrect way by using `lib-opencl (OpenCL library (stubs on Android))`. Unfortunately, `libOpenCL.so` cannot be obtained via `apt install`. On my RK3399, it is located at `/usr/lib/arm-linux-gnueabihf/libOpenCL.so`, which CK usually has no issue detecting. I guess your board has the preinstalled filesystem image, without `libOpenCL.so`. Mine was downloaded from [here](http://bbs.t-firefly.com/forum.php?mod=viewthread&tid=1876&extra=page%3D1). (If you find a newer one, please let me know.)

If that's indeed the issue, you will probably need to reinstall the board and start from scratch. If you do, take care to install the headers *before* installing Caffe:
```
$ sudo apt install opencl-headers
```
as otherwise you may run into other issues.

Hope this helps!

**Comment by psyhtest** [comment]
By the way, here's OpenCL driver info from my board:
```
$ ck run program:tool-print-opencl-devices | grep "version:"
OpenCL 1.2 v1.r13p0-00rel0-git(a4271c9).1ad3fc5b648bfed782705ad469a9797a
```

**Comment by gfursin** [comment]
BTW, if you want to try and re-register opencl, you need first to delete the old CK env via:
```
$ ck rm env:a44911ecc006c67d
```
and then try again (after obtaining a correct libOpenCL version as suggested by @psyhtest psyhtest):
```
$ ck detect soft:lib.opencl
```
If CK still picks up wrong version, you can force the correct one as following:
```
$ ck detect soft:lib.opencl --full_path={FULL PATH to libOpenCL.so}
```
Then you can restart caffe build. BTW, CK should detect that dependency changed and will suggest you to remove outdated sub-dependencies (such as CLBlast and ViennaCL) before reinstalling them ...
Hope it will help!

**Comment by dohai90** [comment]
@gfursin The issue has been resolved by
`$ ck rm env:a44911ecc006c67d`
and
`$ ck detect soft:lib.opencl`

@psyhtest You can find other firmware for firefly rk3399 at this link: [http://en.t-firefly.com/doc/download/index/id/3.html](url)

Thank you for your help :+1:

**Comment by gfursin** [comment]
Cool! You are welcome @dohai90 !
