### ISSUE TITLE
ck compile error --target_os=android21-arm

### ISSUE THREAD

**Issue by Ziv-Huang** [dividiti/ck-caffe#138]

**Comment by psyhtest** [comment]
@Ziv-Huang Hope you've managed to resolve your issue. The error was coming from [repo:ck-caffe-firefly-rk3399](https://github.com/dividiti/ck-caffe-firefly-rk3399/) which actually is not needed for correct operation of CK-Caffe. I'd be interested to hear what you are trying to do.
