### ISSUE TITLE
Enable HDF5 support at caffe for android

### ISSUE THREAD

**Issue by DVEfremov** [dividiti/ck-caffe#15]
Now caffe for android compiles and runs without HDF5
it disable at commit like 
https://github.com/DVEfremov/caffe/commit/c9abe3ac397af5729e38a947f52a270c616e4f73

but it's not clear for now why it does not work for android.
In scope of this issue need to investigate and try to enable HDF5 for android and get caffe-time program work

**Comment by gfursin** [comment]
I don't think we should bother with that on Android (at least at this stage) - if I am correct, it's mostly needed to efficiently process huge amount of images (or other artifacts) during training, which we will unlikely to do on Android. Instead we may do small re-training (when having unexpected behavior or misclassification) or do more time-consuming re-training on a server (for example via CK API with web-service for predictive analytics)...

**Comment by gfursin** [comment]
I think this ticket is outdated (we do not need it at this stage), so I close it.
