### ISSUE TITLE
Problem with "caffe-time" program when using CUDA-based caffe

### ISSUE THREAD

**Issue by gfursin** [dividiti/ck-caffe#18]
I tried to run "caffe-time" with CUDA-based Caffe and got an error:
 I0101 20:51:58.352697 139585 caffe.cpp:61] *** Benchmark begins ***
      I0101 20:51:58.352701 139585 caffe.cpp:62] Testing for 2 iterations.
      F0101 20:51:58.352715 139585 layer.hpp:483] Unknown caffe mode.

At the same time "ck run program:caffe" when selecting time_gpu works fine ...

Any clues?

**Comment by psyhtest** [comment]
As I understand, `caffe-time` is a simplified version of the `caffe` tool that can only be used to time execution. It currently explicitly hardcodes:
```
  // Set device id and mode
  LOG(INFO) << "Use CPU.";
  Caffe::set_mode(Caffe::CPU);
  Net<float> caffe_net(modelFilePath, phase, iterations, &stages);
```
which I suspect is the problem.

**Comment by gfursin** [comment]
Oh, I see - I have to admit I didn't look at inside of the source (shame on me - just didn't have time). However, I just though that it was a clone of the caffe time routine which supports not only CPU but also all other modes such as CUDA ... However, since we make it as a small tool to benchmark models across different devices including Android and we want to have OpenCL there (or CUDA on traditional devices), maybe it's not difficult to add support for OpenCL/CUDA there?
@DVEfremov, what do you think? Thanks a lot!

**Comment by DVEfremov** [comment]
Yes cafe-time now is minimal workable CPU version just to make sure it works at all.
Now I see I can add other options manually without gflag (problem for android version only in gflag lib). 
Will do today.

**Comment by DVEfremov** [comment]
PR #21 contains full functional caffe version with same commands and options but without gflag so it works  for android. 

One limitation for option usage:
* gflag allow to use many variant of option definition like 
  *   -key=value 
  *  --key=value 
  *  -key value 
  *  --key value 

but at my version works only (as already defined at meta for caffe program)
*  --key=value

**Comment by DVEfremov** [comment]
I've fixed a couple of minor issues and merged last changes from master.
Checked compile/run - works fine.

**Comment by gfursin** [comment]
Please, see comments in #21. I close this issue ...
