### ISSUE TITLE
Improve CK-Caffe installation paths

### ISSUE THREAD

**Issue by psyhtest** [dividiti/ck-caffe#2]
I have installed several  variants of Caffe on an Odroid XU3 board with the following paths under `~/CK_TOOLS/`:

```
lib-caffe-bvlc-master-trunk-gcc-5.4.0-lib.openblas-0.2.18-12ab180-linux-32/
lib-caffe-bvlc-opencl-trunk-gcc-5.4.0-lib.openblas-0.2.18-12ab180-lib.viennacl-1.7.1-77e9049-lib.clblas-2.4-03d7e7e-linux-32/
lib-caffe-bvlc-opencl-trunk-gcc-5.4.0-lib.openblas-0.2.18-12ab180-lib.viennacl-1.7.1-77e9049-linux-32/
lib-caffe-bvlc-opencl-trunk-llvm-3.8.0-2ubuntu4-lib.openblas-0.2.18-12ab180-lib.viennacl-1.7.1-77e9049-lib.clblast-mali-overlay-641bb07-linux-32/
lib-caffe-bvlc-opencl-trunk-llvm-3.8.0-2ubuntu4-lib.openblas-0.2.18-12ab180-lib.viennacl-1.7.1-77e9049-linux-32/
```

I suggest two improvements to how installation paths are generated:
- Include a Git revision of Caffe used (instead of `trunk`).
- Remove Git revisions from fixed releases of libraries (e.g. OpenBLAS 0.2.18, ViennaCL 1.7.1, clBLAS 2.4), but not from development branches (e.g. `lib.clblast-mali-overlay-641bb07`).

**Comment by gfursin** [comment]
There is a problem implementing that (at least with my knowledge). When installing a package, I first prepare a path, then make git clone, and only then get revision. Changing the order may complicate things. In a longer term, I would prefer to move GIT URL + branch info to the package meta, so that CK could handle that. Then we can have more flexibility to implement above naming convention.
By the way, anyone knows how to get a git hash of the remote repo?

**Comment by psyhtest** [comment]
> I would prefer to move GIT URL + branch info to the package meta,

Agree. We already have URLs and branches in CK-Caffe packages' metadata e.g. in `ck-caffe/package/lib-caffe-bvlc-opencl-clblast/.cm/meta.json`:

```
  "customize": {
    "extra_dir": "",
    "install_env": {
      "CAFFE_BRANCH": "opencl",
      "CAFFE_URL": "https://github.com/BVLC/caffe"
    },
```

This can be naturally generalised to VCS (version control system) parameters e.g.:

```
    "vcs_params": {
      "branch": "opencl",
      "url": "https://github.com/BVLC/caffe",
      "type": "git"
    },
```

(The latter to handle other types of VCSs.)

> By the way, anyone knows how to get a git hash of the remote repo?

The required Git command is: 

```
$ git ls-remote ${CAFFE_URL} ${CAFFE_BRANCH}
```

or to get a standard short hash (i.e. hash characters 1-7):

```
$ git ls-remote ${CAFFE_URL} ${CAFFE_BRANCH} | cut -c1-7
```

For example, to get the latest commit at the OpenCL branch of the official Caffe repository:

```
$ git ls-remote https://github.com/BVLC/caffe opencl
b0fc44c23848de41ebe5adc7c67244e7f6d77cac        refs/heads/opencl
$ git ls-remote https://github.com/BVLC/caffe opencl | cut -c1-7
b0fc44c
```

**Comment by psyhtest** [comment]
Handing of installation paths has been changed since this ticket was created, hence closing.
