### ISSUE TITLE
Compilation finishes with errors for caffe-time-opencl program for clean ck env

### ISSUE THREAD

**Issue by DVEfremov** [dividiti/ck-caffe#26]
**1) Problem with GLOG**
Steps to reproduce 
* Update / install last ck-caffe version 
* Run 
```ck compile program:caffe-time --target_os=android21-arm-v7a```
* Select 
0) lib-caffe-bvlc-master-opencl-clblast-android  Version trunk  (ee40cd9f86372b7e)
or 
1) lib-caffe-bvlc-master-cpu-android  Version trunk  (4364843d31120476)

* Get error like 
```
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/parallel.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/daniil/CK-TOOLS/lib-caffe-bvlc-master-trunk-android-ndk-4.9.x-android21-arm-v7a-32/src/src/caffe/util/signal_handler.cpp:2:26: fatal error: glog/logging.h: No such file or directory
 #include <glog/logging.h>
                          ^
compilation terminated.
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/util/signal_handler.cpp.o] Error 1
/home/daniil/CK-TOOLS/lib-caffe-bvlc-master-trunk-android-ndk-4.9.x-android21-arm-v7a-32/src/src/caffe/common.cpp:2:26: fatal error: glog/logging.h: No such file or directory
 #include <glog/logging.h>
                          ^
compilation terminated.
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/common.cpp.o] Error 1
In file included from /home/daniil/CK-TOOLS/lib-caffe-bvlc-master-trunk-android-ndk-4.9.x-android21-arm-v7a-32/src/src/caffe/util/benchmark.cpp:3:0:
/home/daniil/CK-TOOLS/lib-caffe-bvlc-master-trunk-android-ndk-4.9.x-android21-arm-v7a-32/src/include/caffe/common.hpp:6:26: fatal error: glog/logging.h: No such file or directory
 #include <glog/logging.h>
                          ^
```

however  

~/CK/ck-caffe/package/lib-caffe-bvlc-master-cpu/.cm/meta.json contains 
contains dependents on 
```
    "lib-glog": {
      "local": "yes",
      "name": "GLog library",
      "sort": 14,
      "tags": "lib,glog"
    },
```

It wasn't installed to ~/CK-TOOLS

**2) Some times I've problem with hdf5**
Steps to reproduce (I'm not sure but some times I've other issues some time this one)
* Update / install last ck-caffe version 
* Run 
```ck compile program:caffe-time --target_os=android21-arm-v7a```
* Select 
1) lib-caffe-bvlc-master-cpu-android  Version trunk  (4364843d31120476)

* Get error like 
```
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
Makefile:566: recipe for target '.build_release/lib/libcaffe.so.1.0.0-rc3' failed
```

**3) Some times I've problem with Protobuf**
Steps to reproduce (I'm not sure but some times I've other issues some time this one)
* Update / install last ck-caffe version 
* Run 
```ck compile program:caffe-time --target_os=android21-arm-v7a```
* Select 
1) lib-caffe-bvlc-master-cpu-android  Version trunk  (4364843d31120476)

* Get error like 
```
nikolay.chunosov [5:13 PM] 
In file included from /home/daniil/CK-TOOLS/lib-protobuf-3.1.0-android-ndk-4.9.x-android21-arm-v7a-32/install/include/google/protobuf/stubs/common.h:41:0,
                from CK_TOOLS_CAFFE/obj/include/caffe/proto/caffe.pb.h:9,
                from CK_TOOLS_CAFFE/obj/include/caffe/proto/caffe.pb.cc:5:
/home/daniil/CK-TOOLS/lib-protobuf-3.1.0-android-ndk-4.9.x-android21-arm-v7a-32/install/include/google/protobuf/generated_message_reflection.h:562:37: note: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::internal::GeneratedMessageReflection&)
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
                                    ^
/home/daniil/CK-TOOLS/lib-protobuf-3.1.0-android-ndk-4.9.x-android21-arm-v7a-32/install/include/google/protobuf/stubs/macros.h:41:3: note: in definition of macro 'GOOGLE_DISALLOW_EVIL_CONSTRUCTORS'
  TypeName(const TypeName&);                           \
  ^
/home/daniil/CK-TOOLS/lib-protobuf-3.1.0-android-ndk-4.9.x-android21-arm-v7a-32/install/include/google/protobuf/generated_message_reflection.h:562:37: note:   candidate expects 1 argument, 9 provided
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
                                    ^
/home/daniil/CK-TOOLS/lib-protobuf-3.1.0-android-ndk-4.9.x-android21-arm-v7a-32/install/include/google/protobuf/stubs/macros.h:41:3: note: in definition of macro 'GOOGLE_DISALLOW_EVIL_CONSTRUCTORS'
  TypeName(const TypeName&);                           \
```

it because host protobuf detect with version 2.9 (from local ubunto env) amd target is used 3.1.0

**Comment by DVEfremov** [comment]
Works fine if do steps as follows 
1) remove CK/CK-TOOLS if exist 
2) install ck-caffe 
$ ck pull repo:ck-caffe --url=https://github.com/dividiti/ck-caffe
3) compile ubuntu cpu version 
$ ck compile program:caffe-classification

4) compile android cpu version 
$ ck compile program:caffe-classification --target_os=android21-arm-v7a

5) compile android opencl version 
$ ck compile program:caffe-classification --target_os=android21-arm-v7a

if you will try to compile android opencl version first willl get inconsistent local env

**Comment by DVEfremov** [comment]
Steps for compilation caffe-opencl-time for android without errors
1)$ ck  compile program:caffe-classification 
2)$ ck  compile program:caffe-classification   --target_os=android21-arm-v7a
3)$ ck  compile program:caffe-time  --target_os=android21-arm-v7a

Other combinations for example compile leads to errors:
1) clean up env / ck /tools 
2) install ck-caffe 
3) $ ck  compile program:caffe-opencl-time  --target_os=android21-arm-v7a

**Comment by gfursin** [comment]
That is very strange - seems like one package is not correctly installed for OpenCL Caffe for Android and requires headers or something else from non-Android package - I will try to check it at some point ...

**Comment by DVEfremov** [comment]
Also some times generated scripts at CK/local/env/<uid>/env.sh 
exports wrong path to libs:
for example 
android libs like gfalg or glog targes to local ubuntu's 
/user/lib dirs

fortunally I cant' provide right step to reproduce but it happens if 
recompile same lib (for example caffe)  with different dependent lib variations

**Comment by gfursin** [comment]
It may happen - the first quick prototype of soft description is usually very simple and I often just append 'lib' or 'include' to the install path. However, with time, we should make them more robust (like in CMake) and make proper detection of all paths ...

**Comment by gfursin** [comment]
And in general, we want to improve soft/env/package one day and make it more formal - I think we have a related ticket about that. But for now, it already lets us do quick prototyping, so it's fine ...

**Comment by DVEfremov** [comment]
Enother case 
I've tried to compile 
ck compile program:caffe-opencl-time --target_os=android21-arm64
just after I've successfully compiled 
ck compile program:caffe-opencl-time --target_os=android21-arm64 

and got error for arm64
```
[  2%] Building CXX object src/caffe/CMakeFiles/caffe.dir/device.cpp.o
/home/daniil/CK-TOOLS/lib-caffe-bvlc-opencl-clblast-android-trunk-android-ndk-4.9.x-1.62.0-0.2.19-85636ff-android21-arm64/src/src/caffe/parallel.cpp:10:26: fatal error: glog/logging.h: No such file or directory
 #include <glog/logging.h>
                          ^
compilation terminated.
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/parallel.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  2%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/signal_handler.cpp.o
/home/daniil/CK-TOOLS/lib-caffe-bvlc-opencl-clblast-android-trunk-android-ndk-4.9.x-1.62.0-0.2.19-85636ff-android21-arm64/src/src/caffe/util/signal_handler.cpp:2:26: fatal error: glog/logging.h: No such file or directory
 #include <glog/logging.h>
                          ^
compilation terminated.
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/util/signal_handler.cpp.o] Error 1
In file included from /home/daniil/CK-TOOLS/lib-caffe-bvlc-opencl-clblast-android-trunk-android-ndk-4.9.x-1.62.0-0.2.19-85636ff-android21-arm64/src/include/caffe/blob.hpp:8:0,
                 from /home/daniil/CK-TOOLS/lib-caffe-bvlc-opencl-clblast-android-trunk-android-ndk-4.9.x-1.62.0-0.2.19-85636ff-android21-arm64/src/include/caffe/device.hpp:18,
                 from /home/daniil/CK-TOOLS/lib-caffe-bvlc-opencl-clblast-android-trunk-android-ndk-4.9.x-1.62.0-0.2.19-85636ff-android21-arm64/src/src/caffe/device.cpp:12:
/home/daniil/CK-TOOLS/lib-caffe-bvlc-opencl-clblast-android-trunk-android-ndk-4.9.x-1.62.0-0.2.19-85636ff-android21-arm64/src/include/caffe/common.hpp:9:27: fatal error: gflags/gflags.h: No such file or directory
 #include <gflags/gflags.h>
                           ^
compilation terminated.
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/device.cpp.o] Error 1
/home/daniil/CK-TOOLS/lib-caffe-bvlc-opencl-clblast-android-trunk-android-ndk-4.9.x-1.62.0-0.2.19-85636ff-android21-arm64/src/src/caffe/common.cpp:2:26: fatal error: glog/logging.h: No such file or directory
 #include <glog/logging.h>
                          ^
compilation terminated.
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/common.cpp.o] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2
Error: build failed!
CK error: [program] package installation failed!

```

**Comment by DVEfremov** [comment]
Looks like it works now (after unifying libs required for caffe-time-opencl).
But need to test with different variations...

**Comment by DVEfremov** [comment]
I've tested many time 
and looks like it works now 
so I'm closing.
