### ISSUE TITLE
lib-viennacl-opencl-trunk-android-ndk-4.9.x-android21-arm-v7a-32 targets to non existed incluede dir 

### ISSUE THREAD

**Issue by DVEfremov** [dividiti/ck-caffe#28]
after installation of lib-viennacl-opencl-trunk-android-ndk-4.9.x-android21-arm-v7a-32 
generates file at CK/local/env with 

export CK_ENV_LIB_VIENNACL_INCLUDE=/home/daniil/CK-TOOLS/lib-viennacl-opencl-trunk-android-ndk-4.9.x-android21-arm-v7a-32/include

but where is no dir 
/home/daniil/CK-TOOLS/lib-viennacl-opencl-trunk-android-ndk-4.9.x-android21-arm-v7a-32/include

so it targets to non existed include dir and compilation for caffe opencl fails

**Comment by gfursin** [comment]
It's likely because I didn't have time to check OpenCL related packages.
This include is normally prepared in soft:lib.viennacl (customize.py) - I guess there is a mistake there ...

**Comment by DVEfremov** [comment]
this issue fixed in scope of ck-caffe/issue/22

**Comment by DVEfremov** [comment]
Fixed at 
https://github.com/ctuning/ck-math/pull/4/
closing
