### ISSUE TITLE
Unify installation process of packages required for ck-caffe programs 

### ISSUE THREAD

**Issue by DVEfremov** [dividiti/ck-caffe#31]
Some packages required for caffe* program compilation are not unified so goal is convert all package installation process to unified as applied already for lib-gflags-2.2.0.

So here is list of packages required for ck-caffe programs  and state (unified or not)
* lib-boost - UNIFIED
* lib-blas - CAN'T FIND PACKAGE WITH THIS NAME
* lib-caffe (lib-caffe-bvlc-opencl-clblast-android) - NOT
  * lib-lmdb - NOT
  * lib-viennacl - PARTLY
    * lib-viennacl-trunk-universal - UNIFIED but need to check, I've selected once and got error 
    * lib-viennacl-trunk-android - NOT
  * lib-clblast (lib-clblas-trunk-android) - NOT

* lib-gflags - UNIFIED 
* lib-glog - UNIFIED
* lib-opencv - UNIFIED
* lib-protobuf (lib-protobuf-3.1.0-android) - UNIFIED
* lib-protobuf-host (lib-protobuf-3.1.0-host) - UNIFIED

**Comment by DVEfremov** [comment]
I've been unifying lib-lmdb at this moment ...

**Comment by gfursin** [comment]
I believe I unified all packages except lib-lmdb ... It would be good to be able to compile for Linux, Android, Windows via our universal install script ... But it's not urgent - more important is to make Caffe OpenCL version work ...

**Comment by gfursin** [comment]
@DVEfremov - after checking latest OpenCL-based Caffe lib and classification across different platforms (some seg faults at the end), do you mind to finish unifying LMDB across Linux, Windows, Android, please? LMDB is really needed for users so this will help us finalize our current Caffe unification... Thanks a lot!

**Comment by DVEfremov** [comment]
ok sure

**Comment by DVEfremov** [comment]
I've applied unification for lib-lmdb-trunk-android
but for android (as it comes from package name)
at PR
https://github.com/ctuning/ck-autotuning/pull/22

@gfursin 
next step 
I  should rename this package lib-lmdb-trunk and check it for linux/windows as well 
am I right?

**Comment by DVEfremov** [comment]
Unified build process for windows but get error on compilation 
![image](https://cloud.githubusercontent.com/assets/22045452/25033454/01ea4ef4-2108-11e7-8c00-569b1826705d.png)

**Comment by gfursin** [comment]
>I should rename this package lib-lmdb-trunk and check it for linux/windows as well
am I right?
Yes, that's right! Thanks!

**Comment by DVEfremov** [comment]
ok, almost done  
I'm in progress with compilation errors under windows

**Comment by gfursin** [comment]
Any progress? Thanks!

**Comment by gfursin** [comment]
I unified all packages including LMDB (i just compile 2 files directly using Visual Studio instead of using Linux make) ... I close this ticket.
