### ISSUE TITLE
Use fresh BVLC/caffe opencl version for android

### ISSUE THREAD

**Issue by DVEfremov** [dividiti/ck-caffe#34]
Need check last BVLC/caffe opencl version how it compiles and work for android. 

It possible use my fork https://github.com/DVEfremov/caffe
new branch opencl_cmake_android from opencl branch of BVLC/caffe with merged commit 
https://github.com/DVEfremov/caffe/commit/c9abe3ac397af5729e38a947f52a270c616e4f73

**Comment by gfursin** [comment]
Let's check it next week - so far I didn't manage to use it (looks like it was missing OpenCL version - maybe wrong commit or I did something wrong) ...

**Comment by DVEfremov** [comment]
Finally I've compiled caffe libs based on github.com/BVLC/caffe branch opencl and it works!
I applied some changes to get it works as follows:

1) I've created fork 
https://github.com/DVEfremov/caffe
from 
BVLC/caffe branch opencl and added some changes to disable HDF5 mostly the same as for master version to my branch opencl_cmake_android
2)  added missed functions for caffe as for clblast
3)  temporary disabled case with multi GPUs support at caffe-time-opencl because of changed API  at BVLC/caffe branch opencl

so next steps is
1) add correct implementation of disableded case with multi GPUs support at caffe-time-opencl

2) check GPU version (for example add GREENTEA e to cmake)

3) update all and check everything once again (now I'm testing on my stable Friday morning version) (edited)

4) make caffe-classification-opencl works

**Comment by DVEfremov** [comment]
All steps listed above implemented.
Found issue with Galaxy S7 - > issue #40 

all my changes applied at fork
https://github.com/DVEfremov/caffe
branch opencl_cmake_android
based on BVLC/caffe branch opencl

**Comment by DVEfremov** [comment]
I'll create separate issue for merge my changes to BVLC/caffe branch opencl
