### ISSUE TITLE
Enable multi GPU support for opencl version caffe.cpp

### ISSUE THREAD

**Issue by DVEfremov** [dividiti/ck-caffe#37]
I've temporary disable multi GPU support at caffe.cpp 
https://github.com/dividiti/ck-caffe/pull/36
because of different API just for fast prototyping and get opencl version work on android as fast as possible at this moment.
In scope of this task I'll enable and check it.

**Comment by gfursin** [comment]
I agree - I also saw this problem, but we can fix it after making Caffe OpenCL work on Android ... Thanks!

**Comment by psyhtest** [comment]
What does 'multi GPU support'? According to [this comment](https://github.com/naibaf7/caffe/issues/61#issuecomment-280616546), multiple GPU is not available on the OpenCL branch anyway. But I don't know what NCCL is.

**Comment by gfursin** [comment]
Is this ticket still valid after all latest updates?

**Comment by DVEfremov** [comment]
yes this issue is not actual because of 
https://github.com/naibaf7/caffe/issues/61

so closing
