### ISSUE TITLE
Automate CK-Caffe benchmarking across nets and libraries

### ISSUE THREAD

**Issue by psyhtest** [dividiti/ck-caffe#4]
This [notebook](https://github.com/dividiti/ck-caffe-explore-batch-size-chromebook2/blob/master/script/explore-batch-size/explore_batch_size.20160809.ipynb) investigates effects on inference performance of varying the batch size:
- across 4 **nets**:
  - [AlexNet](https://github.com/BVLC/caffe/tree/master/models/bvlc_alexnet)
  - [SqueezeNet 1.0](https://github.com/DeepScale/SqueezeNet/tree/master/SqueezeNet_v1.0)
  - [SqueezeNet 1.1](https://github.com/DeepScale/SqueezeNet/tree/master/SqueezeNet_v1.1)
  - [GoogleNet](https://github.com/BVLC/caffe/tree/master/models/bvlc_googlenet)
- with 4 BLAS **libraries**:
  - [CPU] [OpenBLAS](https://github.com/xianyi/OpenBLAS) 0.2.18 (one thread per core);
  - [GPU] [clBLAS](https://github.com/clMathLibraries/clBLAS) 2.4 (OpenCL 1.1 compliant);
  - [GPU] [CLBlast](https://github.com/CNugteren/CLBlast) dev (35623cd > 0.8.0);
  - [GPU] [CLBlast](https://github.com/CNugteren/CLBlast) dev (35623cd > 0.8.0) with Mali-optimized [overlay](https://github.com/intelfx/CLBlast/tree/mali-overlay) (641bb07).

This involved installing the 4 nets, building Caffe for each of the 4 libraries, and repeating the following steps from the `ck-caffe/script/explore-batch-size` directory:
- Running:

```
$ ./_clean_program_pipeline.sh
$ ./_setup_program_pipeline.sh
```
- Selecting:
  - the desired build (e.g. CLBlast with Mali-optimized overlay);
  - the desired net (e.g. AlexNet)
- Running e.g.:

```
$ ./explore_batch_size_alexnet_clblast_mali_overlay.sh
```

In fact, the difference between the `./explore_batch_size_*.sh` scripts is only in where the experimental results are to be recorded (e.g. `caffe-explore-batch-size-alexnet-clblast-mali-overlay`) and with which tags (e.g. `time,caffemodel,alexnet,clblast,vmali-overlay`). Therefore, it is unfortunately possible to record experimental results into a wrong place and with wrong tags.

This ticket proposes to automate this process. One idea is to create a web-based interface that would allow the user to select the desired nets and libraries. This interface could have an option where to store them as well (locally or in a remote repository). 

A further refinement would be to allow the user not only to benchmark on the current machine  (running the web  service) but to specify targets (e.g. for execution via `ssh` or `adb`).

Further ideas (and of course help with implementation) are very welcome!

**Comment by bhack** [comment]
What about the direct convolution of libdnn?

**Comment by psyhtest** [comment]
We already support libDNN (in fact, 4 flavours: with CUDA, ViennaCL, clBLAS and CLBlast). I will release some experimental data shortly. What we need is a tighter integration of lidDNN tuning with CK-Caffe.

**Comment by bhack** [comment]
Oh thank you I supposed that libdnn was between the lines ;). We are using [standalone version](https://github.com/naibaf7/libdnn) in [tiny-dnn](https://github.com/ctuning/ck-tiny-dnn)

**Comment by bhack** [comment]
One of the point is that CLBlast use CLTune for tuning and libdnn it is own tuning component cause kernel tuning approach and strings handling are quite different. Also for Opencl and CUDA bootstrap and kernel launch libdnn use viennacl and CLBlast CLCUDAAPI. In tiny-dnn we adopted CLCUDAAPI but upstream in libdnn we have tuning, bootstrap and lanuch components replicated in libdnn.

**Comment by gfursin** [comment]
Well, CK operates on a higher level, i.e. it is possible to plug in to CK-based crowd-tuner any workload and even sub-tuner (such as CLBlast, Open Tuner, or libDNN tuner), describe what to tune and what to collect (execution time, accuracy, memory foot print, energy), then compile/run/crowd-tune it across different machines and share knowledge. Depending on the time (which we sadly do not have now), I actually hope to add CLBlast to CK crowd-tuner as a demo before Q1 2017. We are also improving our Android application to let user crowdsource such experiments and plan to release new version integrated with CK by the end of this month. And @psyhtest is currently improving performance analysis and autotuning on intermediate (individual library) level. Whenever we have more results, I will immediately send an update!

**Comment by bhack** [comment]
Yes IMHO from our third party point of view the problem is more related to all the code duplicated required to bootstrap opencl, compile program and launch the kernel for benchmarking that is required by each tuning sub implementation. Probably separating pure tuning (kernel code generation) and timing components from device setup, program compiling and exectuion could let to have less duplicated components.

**Comment by gfursin** [comment]
I totally agree with that! In fact, one the reasons why I developed CK is to stop researchers and engineers continuously duplicate various tools, but reuse existing ones with some common and simple API ;) ... But persuading users unify techniques and tools is very hard ;) . That's why we continue working on our universal experimentation framework (compilation, execution, autotuning, replay, etc) and build a community of like-minded people. I mainly focus on an abstract, high-level autotuning/timing in the CK while @psyhtest  and other colleagues work on unifying intermediate OpenCL/CUDA part (see https://github.com/dividiti/gemmbench - this was our first shoot in that direct)). We just want to show that it is possible to unify various frameworks under one umbrella using simple wrappers and maybe this will persuade third-party stop duplicating all the infrastructure but gradually convert them into common framework. We will see ;) ...

**Comment by bhack** [comment]
In gemmbench I see that you are still handling pure Opencl cl2.hpp object. We found that unfied CLCUDAAPI is very useful also if it is still  
not covering all the cases. I.e. the problem with some standards is that there are always extension or corner cases ;). I.e. See https://github.com/CNugteren/CLCudaAPI/issues/11

**Comment by gfursin** [comment]
That's right - GemmBench was more about testing high-level CK 
crowd-tuning concept
and showing how authors could share their workloads and crowdsource 
optimization
using CK. We plan to extend it in Q1 2017, so I added your note there:
https://github.com/dividiti/gemmbench/issues/5
Thanks!

**Comment by psyhtest** [comment]
This is mostly implemented via a new [script](https://github.com/dividiti/ck-caffe/blob/master/script/explore-batch-size-libs-models/explore-batch-size-libs-models-benchmark.py) which benchmarks the cross-product of libraries and models available on the machine, and specified batch sizes. No web interface yet, but it's a big improvement so I'm closing this ticket.
