### ISSUE TITLE
Caffe OpenCL CLBlast fails on x86 on Daniil's branch

### ISSUE THREAD

**Issue by gfursin** [dividiti/ck-caffe#43]
When using new OpenCL branch from Daniil, some OpenCL packages work fine, but the one with CLBlast (used in Android) fails on x86 server with GTX 1080. Original BVLC branch works though.

To reproduce:
$ ck install package:lib-caffe-bvlc-opencl-clblast-universal
$ ck run program:caffe
choose test_gpu + googlenet ...

Log for classification and time are attached.
Thanks!

[log_classification.txt](https://github.com/dividiti/ck-caffe/files/734816/log_classification.txt)
[log_time.txt](https://github.com/dividiti/ck-caffe/files/734817/log_time.txt)

**Comment by DVEfremov** [comment]
I've reproduced locally 
and got additional cl compilation error info:

```
      Build Status = -2 ( Err = -11 )
      Log: Compilation started
      1:10716:5: error: call to 'native_powr' is ambiguous
      <stdin>:1006:61: note: candidate function
      <stdin>:1340:72: note: candidate function
      <stdin>:1007:62: note: candidate function

...
```

**Comment by DVEfremov** [comment]
Issue fixed. 
It works fine now for linux and android as well

**Comment by DVEfremov** [comment]
So second usage of same kernel could be loaded from cache. I suppose cache path should be set before first kernel init:
```
void viennacl::ocl::context::cache_path	(	std::string 	new_path	)	
```

See fore details: http://viennacl.sourceforge.net/doc/classviennacl_1_1ocl_1_1context.html#a6aa5ef5cb563ed047ff72f286eb5718b
