### ISSUE TITLE
Specify program:caffe dependencies per command

### ISSUE THREAD

**Issue by psyhtest** [dividiti/ck-caffe#5]
Currently, CK-Caffe supports the following commands:

```
0) query_gpu_cuda (caffe.bin device_query --gpu=$<<CK_CAFFE_GPU_ID>>$)
1) query_gpu_greentea (caffe.bin device_query)
2) test_cpu (caffe.bin test --model=$<<CK_CAFFE_MODEL>>$ --weights=$<<CK_ENV_MODEL_CAFFE_WEIGHTS>>$ --iterations=$<<CK_CAFFE_ITERATIONS>>$)
3) test_gpu (caffe.bin test --model=$<<CK_CAFFE_MODEL>>$ --weights=$<<CK_ENV_MODEL_CAFFE_WEIGHTS>>$ --iterations=$<<CK_CAFFE_ITERATIONS>>$ --gpu=$<<CK_CAFFE_GPU_ID>>$)
4) time_cpu (caffe.bin time --model=$<<CK_CAFFE_MODEL>>$ --iterations=1)
5) time_gpu (caffe.bin time --model=$<<CK_CAFFE_MODEL>>$ --gpu=$<<CK_CAFFE_GPU_ID>>$ --iterations=1)
```

As can be seen, commands 0-1 (`query_gpu_*`) require neither weights nor a model specified; commands 2-3 (`test_*`) required both weights and a model; commands 4-5 (`time_*`) require only a model. However, even if a user is only interested in evaluating the execution time (`time_*`), she needs to select weights and a data set (e.g. a selection from the ImageNet validation set) which make sense only for evaluating the accuracy (`test_*`). In other words, at the moment dependencies are specified per program, whereas it would be nice to specify dependencies per command.

I know it's not how CK works at the moment. Still, longer term it would be nice to select a command first and then have its dependencies resolved, not the other way round.

**Comment by gfursin** [comment]
I think I updated all that (I provided lots of new functionality, so one should do 'ck pull all'). Please, close this issue, if you check and it works ... Thanks!

**Comment by psyhtest** [comment]
I believe it does - many thanks!
