### ISSUE TITLE
Should cuDNN variants be offered for program:caffe-time-cuda?

### ISSUE THREAD

**Issue by psyhtest** [dividiti/ck-caffe#55]
With no CUDA packages installed, `ck compile program:caffe-time-cuda` offers the following variants:
```
0) lib-caffe-nvidia-0.15-cuda  Version 0.15  (ba8977414d4bc3ac)
1) lib-caffe-nvidia-fp16-emu-cuda  Version fp16-emu  (df40f0a871a78c0d)
2) lib-caffe-nvidia-fp16-cuda  Version fp16  (f12448e45bc8909e)
3) lib-caffe-bvlc-opencl-libdnn-cuda  Version trunk  (21f41e7ad6e07442)
4) lib-caffe-bvlc-master-cuda  Version trunk  (628eb20eaf9449b9)
```
Clearly, this list doesn't include any of cuDNN variants, which perhaps could also be used with the same program (saving on creating `program:caffe-time-cudnn`). Should the user be offered them too?

**Comment by gfursin** [comment]
I agree - I updated meta of CUDNN packages. Do you mind to check it and close this ticket, please, if works? Thanks!

**Comment by psyhtest** [comment]
Yes, thank you!
