### ISSUE TITLE
Unifying CUDA/cuDNN packages

### ISSUE THREAD

**Issue by gfursin** [dividiti/ck-caffe#56]
At some point, we need to convert lib-caffe-bvlc-master-cuda & lib-caffe-bvlc-master-cudnn to the universal installer format similar to lib-caffe-bvlc-opencl-viennacl-universal to support both Linux and Windows. Help is appreciated.

**Comment by psyhtest** [comment]
After removing the useless fp16-emu packages, we have the following:
```
$ ck search package --tags=lib,caffe,vcuda                        
ck-caffe:package:lib-caffe-bvlc-opencl-libdnn-cuda
ck-caffe:package:lib-caffe-nvidia-fp16-cuda
ck-caffe:package:lib-caffe-nvidia-0.15-cuda
ck-caffe:package:lib-caffe-bvlc-master-cuda
$ ck search package --tags=lib,caffe,vcudnn
ck-caffe:package:lib-caffe-bvlc-master-cudnn
ck-caffe:package:lib-caffe-nvidia-0.15-cudnn
ck-caffe:package:lib-caffe-nvidia-fp16-cudnn
```

`lib-caffe-bvlc-opencl-libdnn-cuda` is actually a libDNN package that happens to use CUDA. I would suggest to unify it similarly to `lib-caffe-bvlc-opencl-libdnn-clblast-universal`.

The `lib-caffe-nvidia-fp16-cuda/cudnn` packages use the stale fp16 experimental branch that might not support recent CMake changes. I would wait until the OpenCL branch supports fp16, and then get rid of them.

This leaves `lib-caffe-bvlc-master-cuda/cudnn` and `lib-caffe-nvidia-0.15-cuda/cudnn` packages for unification.

**Comment by DVEfremov** [comment]
Looks like it works now for ubuntu 
lib-caffe-bvlc-master-cuda-universal
and 
lib-caffe-bvlc-master-cudnn-universal

**Comment by DVEfremov** [comment]
I have no windows with cuda support so I cant check it for windows.
Need help here.

**Comment by gfursin** [comment]
I believe I fixed all that. I close this ticket and we will open a new one if there are issues ...
Thanks!
