### ISSUE TITLE
Only show commands that are applicable for a selected variant of Caffe

### ISSUE THREAD

**Issue by psyhtest** [dividiti/ck-caffe#6]
CK-Caffe provides several packages for building Caffe. If no package is installed, the user is offered to install one of them when running `program:caffe` for the first time e.g.:

```
0) lib-caffe-bvlc-viennacl  Version trunk  (fb719b000a68400f)
1) lib-caffe-bvlc-opencl-clblast  Version trunk  (6064ee0a50aac353)
2) lib-caffe-bvlc-opencl-clblas  Version trunk  (57c86c246c232d3f)
3) lib-caffe-bvlc-master-cuda  Version trunk  (628eb20eaf9449b9)
4) lib-caffe-bvlc-master  Version trunk  (14c56f748be92b38)
```

Once a package is installed, the user is offered to choose one of the available commands e.g:

```
0) query_gpu_cuda (caffe.bin device_query --gpu=$<<CK_CAFFE_GPU_ID>>$)
1) query_gpu_greentea (caffe.bin device_query)
2) test_cpu (caffe.bin test --model=$<<CK_CAFFE_MODEL>>$ --weights=$<<CK_ENV_MODEL_CAFFE_WEIGHTS>>$ --iterations=$<<CK_CAFFE_ITERATIONS>>$)
3) test_gpu (caffe.bin test --model=$<<CK_CAFFE_MODEL>>$ --weights=$<<CK_ENV_MODEL_CAFFE_WEIGHTS>>$ --iterations=$<<CK_CAFFE_ITERATIONS>>$ --gpu=$<<CK_CAFFE_GPU_ID>>$)
4) time_cpu (caffe.bin time --model=$<<CK_CAFFE_MODEL>>$ --iterations=1)
5) time_gpu (caffe.bin time --model=$<<CK_CAFFE_MODEL>>$ --gpu=$<<CK_CAFFE_GPU_ID>>$ --iterations=1)
```

A user common mistake is to select a command that's not applicable to the selected package which all ends up in tears. For example, only commands `test_cpu` (command choice 2) and `time_cpu` (command choice 4) are applicable to `lib-caffe-bvlc-master` (package choice 4); only commands `query_gpu_cuda` (command choice 0), `test_gpu` (command choice 3) and `time_gpu` (command choice 5) are applicable to `lib-caffe-bvlc-master-cuda` (package choice 3), and so on.

It would be nice to only present commands that are applicable to a selected Caffe package.

**Comment by psyhtest** [comment]
@gfursin I believe this is done now, albeit in a reverse fashion: first the user gets asked about the command, then is offered to select or install a package?

**Comment by gfursin** [comment]
Yeap! That's right. I close this ticket!
