### ISSUE TITLE
Need a hack to build caffe on Windows machine

### ISSUE THREAD

**Issue by Chunosov** [dividiti/ck-caffe#62]
I have a clean windows system and install prerequisites: MS Visual Studio 2015 Community, CMake, MinGW, Python, git. Clone ck-caffe repo and try to build:
`ck compile program:ck-classification`
it fails with message:
```
CK error: [program] can't find CK_MAKE_GENERATOR in CK description of Microsoft compiler!
```
search for compiler as
`ck search env --tags=compiler,microsoft`
go to env folder and manually add line 
`"CK_CMAKE_GENERATOR": "Visual Studio 14"`
into meta.json in _env_ section, and line 
`set CK_CMAKE_GENERATOR=Visual Studio 14` 
into env.bat
Then compile process can step forward.

**Comment by Chunosov** [comment]
Please, note that it should be `Visual Studio 14 2015 Win64` for 64-bit OS

**Comment by gfursin** [comment]
Hmm, it should have been detected automatically by soft:compiler.microsoft, unless something wrong have happened. I slightly improved it and added text to open an issue with some debug info if such case again happens:
    if env.get('CK_CMAKE_GENERATOR','')=='':
       ck.out('**********************************')
       ck.out('Problem: can\'t detect Visual Studio compiler version from ('+str(sver)+')')
       ck.out('')
       ck.out('Please report to the authors at https://github.com/ctuning/ck-env/issues')
       ck.out('')
       r=ck.inp({'text':'Would you like to continue installation (Y/n): '})
       if r['return']>0: return r
       rx=r['string'].strip().lower()
       if rx=='n' or rx=='no': 
          return {'return':1, 'error':'can\'t detect Visual Studio compiler version'}

I close this ticket for now ... Thanks for reporting!
