### ISSUE TITLE
Need MSYS path to build caffe on Windows machine

### ISSUE THREAD

**Issue by Chunosov** [dividiti/ck-caffe#63]
msys dir must be added to PATH to make compilation of lib-openblas working.
MinGW installer does modify PATH variable by default.

1) script download-and-install-package/install.bat contains calls like sleep 2, but Windows has not this command (reported here https://github.com/ctuning/ck-env/issues/20)
2) makefile for lib-openblas calls for 'uname' and 'perl' which are not available by default and contained in msys

It seems, installation guide for window should note about it.

**Comment by Chunosov** [comment]
Actually, openblas's wiki (https://github.com/xianyi/OpenBLAS/wiki/Installation-Guide) tells about this requirement:
```
In order to build OpenBLAS on Windows you will need:
MSYS (a collection of Unix tools, including "make"). We recommend this distribution: http://sourceforge.net/projects/mingwbuilds/files/external-binary-packages/
```

**Comment by gfursin** [comment]
I am trying to minimize dependencies. I fixed the problem with sleep, and as for the second part, I use mingw32-make.exe from MingW GCC so normally it should not require MSYS (I think perl is not strictly necessary). But we will test it soon on a Windows 10 Surface Pro which we should get soon...

**Comment by gfursin** [comment]
I believe I fixed that. I added detection of Unix Utils on Windows and in fact they are available in the Git installation (if selecting option of Unix utils), or they will be also detected if downloaded and unzipped manually to a user space ... I close this ticket ...
