### ISSUE TITLE
misused "dynamic_lib" and "static_lib" in meta.json of hdf5 package on Windows

### ISSUE THREAD

**Issue by Chunosov** [dividiti/ck-caffe#66]
In local env of hdf5 package on Windows keys "dynamic_lib" and "static_lib" are misused
```
"dynamic_lib": "libhdf5.lib", 
...
"static_lib": "libhdf5.dll",
```
obviously *.lib is static, not dynamic, and vice versa.

**Comment by Chunosov** [comment]
It seems that 'lib' prefix here is redundant too. Files are called _hdf5.lib_ and _hdf5.dll_

**Comment by gfursin** [comment]
Thanks, I fixed dynamic vs static lib. As for libhdf5 - actually both are generated on my system, so I automatically detect first libhdf5.lib and then hdf5.lib ...
