### ISSUE TITLE
Remove DNN proxies once the demo app redesign is merged

### ISSUE THREAD

**Issue by dsavenko** [dividiti/ck-caffe#83]
Hi,

We will need to remove DNN proxies once https://github.com/dividiti/crowdsource-video-experiments-on-desktop/pull/24 is merged. The proxies are actually a hack for old demo app to work, and we should strive for not having dead code in repos.

**Comment by gfursin** [comment]
Done! Moved to ck-old-packages repo (the DLL usage can still be useful one day) ...

**Comment by dsavenko** [comment]
Typically, Git tags are used to mark outdated content - this way, you can always bring it back. But, I guess, moving into a separate repo works as well.

**Comment by gfursin** [comment]
Well, it's not exactly the same - packages is a high level CK functionality and want to still have them in a working state somewhere, rather then do something with Git. I.e. I can just pull that repo and immediately use these packages ...
