### ISSUE TITLE
Add support for SSD

### ISSUE THREAD

**Issue by psyhtest** [dividiti/ck-caffe#85]
SSD is a Single Shot MultiBox Detector ([paper](http://arxiv.org/abs/1512.02325), [slides](http://www.cs.unc.edu/~wliu/papers/ssd_eccv2016_slide.pdf)).

Add CK-Caffe support for:
- the [SSD](https://github.com/weiliu89/caffe/tree/ssd) fork of Caffe;
- the [COCO](http://mscoco.org/) dataset;
- the [VOC](http://host.robots.ox.ac.uk/pascal/VOC) dataset:
  - VOC2007 - [trainval](http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtrainval_06-Nov-2007.tar), [test](http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtest_06-Nov-2007.tar) (last VOC competition to publish test data)
  - VOC2012 - [trainval](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar)
- pretrained SSD300 and SSD500 models (see [README](https://github.com/weiliu89/caffe/blob/ssd/README.md))
- implement the accuracy metrics and reproduce the [table](https://camo.githubusercontent.com/2342b1174a343d30802dc8fc9acd8b59dc2556d5/687474703a2f2f7777772e63732e756e632e6564752f7e776c69752f7061706572732f7373645f726573756c74732e706e67)
- implement the performance metrics (fps)

**Comment by DVEfremov** [comment]
Do we need this package for linux only or for windows as well ?

**Comment by dsavenko** [comment]
As discussed elsewhere, we need it to be cross-platform if possible.
