### ISSUE TITLE
Add support for ResNet

### ISSUE THREAD

**Issue by psyhtest** [dividiti/ck-caffe#87]
Microsoft Research Asia designed several [Deep Residual Networks](https://github.com/KaimingHe/deep-residual-networks).

Add CK-Caffe support for:
- the ResNet50 model ([weights](https://deepdetect.com/models/resnet/ResNet-50-model.caffemodel), [topology](https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-50-deploy.prototxt))
- the ResNet101 model ([weights](https://deepdetect.com/models/resnet/ResNet-101-model.caffemodel), [topology](https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-101-deploy.prototxt))
- the ResNet152 model ([weights](https://deepdetect.com/models/resnet/ResNet-152-model.caffemodel), [topology](https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-152-deploy.prototxt))

Note that the model topologies are from the [official ResNet GitHub page](https://github.com/KaimingHe/deep-residual-networks/tree/master/prototxt), while the weights are from a [mirror](https://deepdetect.com/models/resnet/). (The [official ResNet weights](https://onedrive.live.com/?authkey=%21AAFW2-FVoxeVRck&id=4006CBB8476FF777%2117887&cid=4006CBB8476FF777) from OneDrive may not be easy to download using a script.)

Note also the use of a special [ResNet_mean.binaryproto](https://deepdetect.com/models/resnet/ResNet_mean.binaryproto).

**Comment by Rhymmor** [comment]
Did I understand correctly that ResNet_mean.binaryproto should be used in caffe classification programs instead of imagenet_mean.binaryproto which is hardcoded into these programs (for default mode) right now?

**Comment by psyhtest** [comment]
That's right. Instead of three copies of `ResNet_mean.binaryproto`, we should ideally  just create a separate package and set up the three ResNet ones to depend on it.

**Comment by psyhtest** [comment]
@Rhymmor, thanks for your contribution!

While you are at it :), could you please also add ResNet10 ([weights](https://github.com/cvjena/cnn-models/blob/master/ResNet_preact/ResNet10_cvgj/model_download_link.txt), all [topologies](https://github.com/cvjena/cnn-models/tree/master/ResNet_preact/ResNet10_cvgj)), which [doesn't require subtracting the mean](https://github.com/cvjena/cnn-models/blob/master/ResNet_preact/ResNet10_cvgj/IMPORTANT)? Please also include a [link to the licensing terms](https://github.com/cvjena/cnn-models/blob/master/LICENSE).

**Comment by Rhymmor** [comment]
@psyhtest, sure!

Hmm, I've tried it in ck and it gives the same poor prediction for any image.

```
---------- Prediction for /home/anatoly/CK/ctuning-datasets-min/dataset/image-jpeg-dnn-cat/cat.jpg ----------
      0.0010 - "n01491361 tiger shark, Galeocerdo cuvieri"
      0.0010 - "n01494475 hammerhead, hammerhead shark"
      0.0010 - "n01443537 goldfish, Carassius auratus"
      0.0010 - "n01440764 tench, Tinca tinca"
      0.0010 - "n01484850 great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias"
```

**Comment by psyhtest** [comment]
@Rhymmor Which program are you using? I've tried `program:caffe-classification` with `resnet50` and got as a sensible result:
```
      ---------- Prediction for /home/anton/CK_REPOS/ctuning-datasets-min/dataset/image-jpeg-dnn-computer-mouse/computer_mouse.jpg ----------
      0.9935 - "n03793489 mouse, computer mouse"
      0.0059 - "n04254680 soccer ball"
      0.0001 - "n03637318 lampshade, lamp shade"
      0.0001 - "n09229709 bubble"
      0.0000 - "n03127747 crash helmet"
```

**Comment by Rhymmor** [comment]
@psyhtest, sorry, my comment wasn't clear. I've implemented and tried resnet10 in ck and get that results. BTW, resnet10 model size is 21 mb, is it normal?

**Comment by psyhtest** [comment]
@Rhymmor Are you surprised it's only 21 MB, not 240 MB like AlexNet? :) Well, that's the whole point - it's a more compact more with good accuracy. (Although not as compact as SqueezeNet which is under 5 MB.)

The results are very strange though. Something's not right. I see that the default command of e.g. `program:caffe-classification-cuda` is:
```
0) default ($#BIN_FILE#$ $<<CK_CAFFE_MODEL_FILE>>$ $<<CK_CAFFE_MODEL_WEIGHTS>>$ $#up_dir#$imagenet_mean.binaryproto $#up_dir#$synset_words.txt $#dataset_path#$$#dataset_filename#$)
```
The use of `$#up_dir#$imagenet_mean.binaryproto` is particularly suspicious here as this model doesn't require subtracting the mean...

**Comment by psyhtest** [comment]
Unfortunately, the direct link no longer works:
```
$ wget https://upload.uni-jena.de/data/58493041de6f79.63214979/resnet10_cvgj_iter_320000.caffemodel
--2017-04-07 20:40:07--  https://upload.uni-jena.de/data/58493041de6f79.63214979/resnet10_cvgj_iter_320000.caffemodel
Resolving upload.uni-jena.de (upload.uni-jena.de)... 141.35.105.30, 2001:638:1558:2369:1:5ee:bad:c0de
Connecting to upload.uni-jena.de (upload.uni-jena.de)|141.35.105.30|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-04-07 20:40:07 ERROR 404: Not Found.
```
And it's not possible to `wget` from Google Drive or Baidu Pan :(. I will close this ticket for now, as we have other priorities.
